# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x06\n\x04Null\"9\n\x05Honey\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\r\"\x1c\n\x0c\x43onfirmation\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t2H\n\x0bTestService\x12\x16\n\x06Health\x12\x05.Null\x1a\x05.Null\x12!\n\x08\x41\x64\x64Honey\x12\x06.Honey\x1a\r.Confirmationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=17
  _NULL._serialized_end=23
  _HONEY._serialized_start=25
  _HONEY._serialized_end=82
  _CONFIRMATION._serialized_start=84
  _CONFIRMATION._serialized_end=112
  _TESTSERVICE._serialized_start=114
  _TESTSERVICE._serialized_end=186
# @@protoc_insertion_point(module_scope)
